name: Build and upload Rust binary to GitHub Releases
description: GitHub Action for building and uploading Rust binary to GitHub Releases

inputs:
  bin:
    description: >
      Comma-separated list of binary names (non-extension portion of filename) to build and upload.
      Note that glob pattern is not supported yet.
    required: true
  archive:
    description: Archive name (non-extension portion of filename) to be uploaded (variables `$bin`, `$target`, `$tag`, and any string)
    required: false
    default: '$bin-$target'
  target:
    description: Target name, default is host triple
    required: false
  features:
    description: Comma-separated list of cargo build features to enable
    required: false
  no_default_features:
    description: Whether to disable cargo build default features
    required: false
    default: 'false'
  manifest_path:
    description: Override cargo manifest path
    required: false
  tar:
    description: On which platform to distribute the `.tar.gz` file (all, unix, windows, or none)
    required: false
    default: 'unix'
  zip:
    description: On which platform to distribute the `.zip` file (all, unix, windows, or none)
    required: false
    default: 'windows'
  include:
    description: >
      Comma-separated list of additional files to be included to archive.
      Note that glob pattern is not supported yet.
    required: false
  asset:
    description: >
      Comma-separated list of additional files to be uploaded separately.
      Note that glob pattern is not supported yet.
    required: false
  leading_dir:
    description: Whether to create the leading directory in the archive or not
    required: false
    default: 'false'
  build_tool:
    description: Tool to build binaries (cargo, cross, or cargo-zigbuild)
    required: false
  checksum:
    description: Comma-separated list of algorithms to be used for checksum (sha256, sha512, sha1, or md5)
    required: false
  token:
    description: >
      GitHub token for creating GitHub Releases.

      If not set this option, the GITHUB_TOKEN environment variable will be used.
    required: false
  ref:
    description: >
      Fully-formed tag ref for this release.

      If not set this option, the GITHUB_REF environment variable (automatically set by GitHub Actions) will be used.
    required: false
  profile:
    description: The cargo profile to build. This defaults to the release profile.
    required: false
    default: 'release'
  pgp_public_key:
    description: >
      Public key used for PGP signing.

      Note: support for signing with PGP is experimental; see <https://github.com/taiki-e/upload-rust-binary-action/issues/40> for details

      This must be an armored key or path to it.
      For example, the file output by the following command:

      > gpg --output <output-path> --armor --export <key-id>

      This key is not strictly needed for signing, but is used to verify that
      signing was done correctly with the private key corresponding to this key.
    required: false
  pgp_private_key:
    description: >
      Private key used for PGP signing.

      Note: support for signing with PGP is experimental; see <https://github.com/taiki-e/upload-rust-binary-action/issues/40> for details

      This must be an armored key. Unlike pgp_public_key, path is not allowed.
      For example, the contents of the file output by the following command:

      > gpg --output <output-file> --armor --export-secret-key <key-id>

      If you have already imported the private key, you do not need to specify this.
    required: false
  pgp_passphrase:
    description: >
      Passphrase of PGP private key. Default to empty string.

      Note: support for signing with PGP is experimental; see <https://github.com/taiki-e/upload-rust-binary-action/issues/40> for details
    required: false
    default: ''
  pgp_sign_target:
    description: >
      Comma-separated list of file kinds to be signed with PGP.

      List can contains any of the followings:
      - checksum: .<checksum> files
      - asset: all assets to be uploaded except for .<checksum> files

      Signing files inside the asset (e.g., rust binaries contained in the
      archive) is not yet supported.

      Note: support for signing with PGP is experimental; see <https://github.com/taiki-e/upload-rust-binary-action/issues/40> for details
    required: false
    default: '' # TODO: default?

# TODO: allow kebab-case input option names?
# Note:
# - inputs.* should be manually mapped to INPUT_* due to https://github.com/actions/runner/issues/665
# - Use GITHUB_*/RUNNER_* instead of github.*/runner.* due to https://github.com/actions/runner/issues/2185
runs:
  using: composite
  steps:
    - run: bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/main.sh"
      shell: bash
      env:
        INPUT_BIN: ${{ inputs.bin }}
        INPUT_ARCHIVE: ${{ inputs.archive }}
        INPUT_TARGET: ${{ inputs.target }}
        INPUT_FEATURES: ${{ inputs.features }}
        INPUT_NO_DEFAULT_FEATURES: ${{ inputs.no_default_features }}
        INPUT_MANIFEST_PATH: ${{ inputs.manifest_path }}
        INPUT_TAR: ${{ inputs.tar }}
        INPUT_ZIP: ${{ inputs.zip }}
        INPUT_INCLUDE: ${{ inputs.include }}
        INPUT_ASSET: ${{ inputs.asset }}
        INPUT_LEADING_DIR: ${{ inputs.leading_dir }}
        INPUT_BUILD_TOOL: ${{ inputs.build_tool }}
        INPUT_CHECKSUM: ${{ inputs.checksum }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_REF: ${{ inputs.ref }}
        INPUT_PROFILE: ${{ inputs.profile }}
        INPUT_PGP_PUBLIC_KEY: ${{ inputs.pgp_public_key }}
        INPUT_PGP_PRIVATE_KEY: ${{ inputs.pgp_private_key }}
        INPUT_PGP_PASSPHRASE: ${{ inputs.pgp_passphrase }}
        INPUT_PGP_SIGN_TARGET: ${{ inputs.pgp_sign_target }}
